use crate::render::Color;

pub(crate) const AXIS_PADDING: f32 = 6.0;
pub(crate) const TICK_LENGTH_MAJOR: f32 = 6.0;
pub(crate) const TICK_LENGTH_MINOR: f32 = 3.0;
pub(crate) const DOUBLE_CLICK_PIN_GRACE_MS: u64 = 1200;
pub(crate) const PIN_RING_INNER_PAD: f32 = 4.0;
pub(crate) const PIN_RING_OUTER_PAD: f32 = 8.0;
pub(crate) const PIN_UNPIN_HIGHLIGHT: Color = Color::new(0.95, 0.25, 0.25, 1.0);
pub(crate) const PIN_LABEL_OFFSET: f32 = 10.0;
pub(crate) const MAX_PIN_LABELS: usize = 12;
pub(crate) const MAX_PIN_LABEL_COVERAGE: f32 = 0.35;
pub(crate) const PIN_CLUSTER_RADIUS: f32 = 40.0;
pub(crate) const LEGEND_FONT_SIZE: f32 = 12.0;
pub(crate) const LEGEND_LINE_HEIGHT: f32 = 16.0;
pub(crate) const LEGEND_PADDING: f32 = 6.0;
pub(crate) const LEGEND_TOGGLE_DIAMETER: f32 = 12.0;
pub(crate) const LEGEND_TOGGLE_INNER_DIAMETER: f32 = 8.0;
pub(crate) const LEGEND_TOGGLE_GAP: f32 = 6.0;
pub(crate) const LEGEND_SWATCH_WIDTH: f32 = 16.0;
pub(crate) const LEGEND_SWATCH_GAP: f32 = 6.0;
pub(crate) const LEGEND_HIDDEN_ALPHA: f32 = 0.35;
pub(crate) const LEGEND_TEXT_HIDDEN_ALPHA: f32 = 0.45;
